backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'public/assets' # Media files will be stored in the repo under static/images/uploads
public_folder: '/assets' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'main-sttings'
    label: 'Site Settings'
    files:
      - label: 'Main Info'
        name: main-info
        file: 'src/data/main-info2.json'
        fields:
          - { label: 'Site Title', name: title, widget: string }
          - { label: 'Main Name', name: name, widget: string }
          - { label: 'Subtitle', name: subName, widget: string }
          - { label: 'Logo', name: logo, widget: image }
